name: Send Task Reminder

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  send_reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send task reminder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          GOOGLE_SHEETS_SHEET_ID: ${{ secrets.GOOGLE_SHEETS_SHEET_ID }}
          GOOGLE_SHEETS_SHEET_LINK: ${{ secrets.GOOGLE_SHEETS_SHEET_LINK }}
        run: |
          python src/task_scheduler.py

      - name: Commit hash file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .last_message_hash
          git commit -m "Update last message hash" || echo "No changes to commit"
          git push
